### ISSUE TITLE
"How to Use Typicons" Typo

### ISSUE THREAD

**Issue by jesseschoff** [stephenhutchings/typicons.font#12]
Hey there,

Thanks so much for these icons! They're great.

Wanted to point out a typo in the ["How to Use Typicons"](http://typicons.com/more/how-to-use-typicons/) that may cause some issues for people.

The HTML usage example doesn't close the `span`:
`<span class="typcn typcn-arrow-left"><span>`

Should be:
`<span class="typcn typcn-arrow-left"></span>`

Also, in the `@font-face` paragraph, it says "cross-bwroser solution"

Thanks again!

**Comment by stephenhutchings** [comment]
Fixed in https://github.com/stephenhutchings/typicons.com/commit/dbc0ae1dc78a301044d379c4862f1d192b7c5cf7
