### ISSUE TITLE
SVG source files unavailable via Bower

### ISSUE THREAD

**Issue by synapticism** [stephenhutchings/typicons.font#13]
Hi there! Love the icons, but would it be possible to include the SVG source files in the Bower package so developers can automate building their own icon sheets?

**Comment by stephenhutchings** [comment]
Sounds like a good improvement. I'll add it to the list of things to achieve in the next release. Unfortunately I'm a bit stretched for time at the moment.

**Comment by synapticism** [comment]
I created a pull request on the off chance this speeds things up!

**Comment by stephenhutchings** [comment]
Merged and bumped version. Cheers!
