### ISSUE TITLE
original Typicons.svg lost?

### ISSUE THREAD

**Issue by wwfalcon** [stephenhutchings/typicons.font#20]
it used in :
https://github.com/stephenhutchings/typicons.font/blob/master/Makefile#L24

but in the master , can not find.

**Comment by stephenhutchings** [comment]
The make file is originally from another project, and the dump command is no longer used. You should still be able to run the Makefile. The source SVG files are located [here](https://github.com/stephenhutchings/typicons.font/tree/master/src/svg).
