### ISSUE TITLE
CSS class for optional sizes

### ISSUE THREAD

**Issue by guoyunhe** [stephenhutchings/typicons.font#21]
Font Awesome has some classes to get bigger icon: fa-lg (150%), fa-2x, fa-3x. It avoids manually coding font-size. Hope Typicons can also support it. If you think it is useful, I can make a pull request. Thanks for your work, it is a nice icon set!

**Comment by stephenhutchings** [comment]
The latest version (2.1.0) now includes sizing utility classes that match the behaviour of Font Awesome.

```
.typcn-lg {
  font-size: 1.33333333em;
  line-height: 0.75em;
  vertical-align: -15%;
}
.typcn-2x {
  font-size: 2em;
}
.typcn-3x {
  font-size: 3em;
}
.typcn-4x {
  font-size: 4em;
}
.typcn-5x {
  font-size: 5em;
}
```
