### ISSUE TITLE
Bower deprecation; add complete project to npm?

### ISSUE THREAD

**Issue by synapticism** [stephenhutchings/typicons.font#23]
[Bower is effectively deprecated](https://github.com/bower/bower/issues/2298), would it be possible to expand what's offered through npm to include source files for those of us who roll out own SVG sprite sheets? The issue is the `files` field in `package.json`; this whitelists what files are included in the published package and only features compiled fonts and files.

**Comment by stephenhutchings** [comment]
Good call. The SVG files are now included in the package @synapticism.

**Comment by synapticism** [comment]
Thanks, I can confirm it works perfectly now!
