### ISSUE TITLE
Use as a web font like Font Awesome

### ISSUE THREAD

**Issue by Nerajno** [stephenhutchings/typicons.font#24]
Greetings, do you have any clues on how to use the font as one would Font Awesome (using a web link) ?

**Comment by stephenhutchings** [comment]
You can find instructions for how to use the font [here](http://typicons.com/more/how-to-use-typicons/). If you are looking for a remote version of the files, you could point to a CDN like the one [here](https://cdnjs.com/libraries/typicons).

**Comment by Zircoz** [comment]
I have installed it using npm. Now how do I use it in my html files? @Nerajno @stephenhutchings
