### ISSUE TITLE
Error when loading fonts in React

### ISSUE THREAD

**Issue by macsee** [stephenhutchings/typicons.font#26]
Hi,
I'm getting this error when using typicons.font in React:

`Failed to compile.
./node_modules/typicons.font/src/font/typicons.css

Module not found: Can't resolve '../../../css-loader/index.js' in '/home/scit/DESARROLLO/iunir/node_modules/typicons.font/src/font'`

Does anyone how to solve this?
Thanks!

**Comment by FuadAliah** [comment]
Same here, any advise

**Comment by stephenhutchings** [comment]
Other libraries like [React Icons](http://react-icons.github.io/react-icons/icons?name=ti) are probably the best way to include Typicons in React projects.
