### ISSUE TITLE
License of css

### ISSUE THREAD

**Issue by deemp** [stephenhutchings/typicons.font#31]
Hi, @stephenhutchings! In https://github.com/deemp/purescript-css-frameworks,  I collect `.css` files and generate class names for PureScript. I included the [typicons.css](https://github.com/stephenhutchings/typicons.font/blob/master/src/font/typicons.css) file there with the CC BY-SA 3.0 license, but recently realized it may be the wrong one. May I leave the `typicons.css` there? What type of license should I write?

**Comment by stephenhutchings** [comment]
Please feel free to include the CSS in your project. The typicons images are distributed under [CC BY-SA](http://creativecommons.org/licenses/by-sa/3.0/) licence.
